# fly.toml app configuration file generated for study-bot-ai on 2024-08-16T14:57:26-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'study-bot-ai'
primary_region = 'gru'

[build]

[[services]]
  internal_port = 3000
  protocol = "tcp"

  # Allow machines to run continuously
  auto_start_machines = false
  auto_stop_machines = false

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
