# fly.toml app configuration file generated for study-bot-ai on 2024-08-16T14:57:26-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'study-bot-ai'
primary_region = 'gru'

[build]

[[services]]
  internal_port = 8888
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

    [[services.ports]]
      handlers = ["http"]
      port = 80
      force_https = false

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
